name: batiksekarniti
description: "Flutter project Batik Sekarniti (merged frontend)"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI & Utilities
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.8.4
  flutter_launcher_icons: ^0.14.4
  provider: ^6.1.2
  intl: ^0.20.2
  shared_preferences: ^2.0.15

  # HTTP & Utilities
  http: ^1.2.0
  uuid: ^4.3.3
  csv: ^6.0.0

  # Firebase
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  firebase_crashlytics: ^5.0.6
  cloud_firestore: ^6.1.1

  # Supabase
  supabase_flutter: ^2.6.0

  # WebView
  webview_flutter: ^4.2.2
  webview_flutter_android: ^4.10.11
  webview_flutter_wkwebview: ^3.10.0

  # Media & File Handling
  image_picker: ^1.2.1
  file_picker: ^10.3.8

  # PDF & Printing
  pdf: ^3.11.3
  printing: ^5.14.2

  # Auth tambahan
  sign_in_with_apple: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - asset/icon/batiksekarniti.png

flutter_launcher_icons:
  android: true
  image_path: "asset/icon/batiksekarniti.png"